### ISSUE TITLE
AbstractPlane::activate() causes assertion failure

### ISSUE THREAD

**Issue by cheezeygeek** [mosra/magnum-extras#12]
It looks like `AbstractPlane::activate` assumes that a plane cannot be both hidden and at the front of the hierarchy, and there is an assertion enforcing this:

https://github.com/mosra/magnum-extras/blob/c13d6e592ab4b4872b42fd85e87df5a8360bdb7c/src/Magnum/Ui/BasicPlane.cpp#L78-L88

In my usage, this assertion has had a lot of failures. For example, if you:

1. Create a UserInterface
2. Add a Plane to it
3. Call Plane::hide()
4. Call Plane::activate()

This causes a crash, even though it seems like perfectly legitimate usage.

I was able to fix it for my purposes by just deleting the if-statement and the two lines inside it. But I suspect that there's a reason that assertion is there, which is why I'm hesitant to submit a PR.

I know this project is on hold, but I thought I would file an issue in case someone picks it up again (or someone with the same problem as me checks the issues for help).

**Comment by mosra** [comment]
Hi!

I think I'm aware of this one, and I have a partial fix on some branch somewhere, but I wanted to improve the test coverage for this behavior and on that it got stuck, basically.

> I know this project is on hold

Yes, sorry, I don't have the "bandwidth" to switch focus to this project to fix this particular issue these days. If you can, please switch to [Dear ImGui](https://magnum.graphics/showcase/imgui/) instead, this lib is extremely limited and underdocumented at this point and I don't want you to suffer by using it.

The `Ui` lib is not dead, though, I want to revive it at some point and continue exploring design directions that are not easy to do with Dear ImGui. So I'm keeping this issue open until I find time to do the fix.

**Comment by mosra** [comment]
The UI lib got completely replaced with a new implementation as of 9d42ea49234c696ea59abdf7b9d2ef11a50f87b1 + f560d2381b5bae3bf20f7a95552370a7a6dd3e00, and this is no longer a bug. And yes, the test coverage is significantly better now.
