### ISSUE TITLE
Error when compiling for Android. ' implicit instantiation of undefined template Attribute<int>'

### ISSUE THREAD

**Issue by Joaqim** [mosra/magnum-extras#4]
Having no luck compiling Ui for Android.
Tested with Android-Studio, gradle command-line and CMake cross-compilation. Same error.
Hoping it's a simple thing like missing Header or something stupid on my part that I've missed.

Full CMake output here: [https://pastebin.com/RfbuWUuf](https://pastebin.com/raw/RfbuWUuf)

`In file included from /opt/android-ndk/sysroot/usr/include/Magnum/GL/Mesh.h:38:
/opt/android-ndk/sysroot/usr/include/Magnum/GL/Attribute.h:84:43: error: implicit instantiation of undefined template 'Magnum::GL::Implementation::Attribute<int>'
            VectorCount = Implementation::Attribute<T>::VectorCount

/home/jq/projects/magnum-extras-clean/src/Magnum/Ui/Plane.cpp:53:100 : note: in instantiation of template class 'Magnum::GL::Attribute<3, int>' requested here
                Implementation::AbstractQuadShader::ColorIndex{Implementation::AbstractQuadShader::ColorIndex::DataType::Short},

/opt/android-ndk/sysroot/usr/include/Magnum/GL/Attribute.h:41:25: note: template is declared here
        template<class> struct Attribute; 
. . . . . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . 
. . . etc
12 errors generated.
make[2]: *** [src/Magnum/Ui/CMakeFiles/MagnumUi.dir/build.make:179: src/Magnum/Ui/CMakeFiles/MagnumUi.dir/Plane.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:141: src/Magnum/Ui/CMakeFiles/MagnumUi.dir/all] Error 2
make: *** [Makefile:130: all] Error 2`

**Comment by mosra** [comment]
Hi, can you share a few details about what compiler, standard library and magnum version you use? I was successfully deploying the Ui Gallery to Android a month ago, so I think there shouldn't be any serious problem.

**Comment by joaqim** [comment]
I'm compiling the standard CMakeFile provided which has succesfully worked with other magnum repositores: magnum and magnum-plugins
And the PKG-android-arm64 for those repositories has worked flawlessly. But I get the same error either way when trying to compile WITH_UI on magnum-extras.

I'm using Android SDK 22 ( provided by android-ndk) but I've also tried an older version.

I'm linking to c++_static llvm ( and I've tried linking c++_glibc
CMakeOutput.log show that I'm using /opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/clang++


with (excluding -isystem includes) : 
'--target=armv7-none-linux-androideabi --gcc-toolchain=/opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64
-march=armv7-a -mthumb -mfpu=vfpv3-d16 -mfloat-abi=softfp -funwind-tables -no-canonical-prefixes -D__ANDROID_API__=22 -fexceptions -frtti  -g -fPIE   -std=c++14'
provided by CMakeLists.txt

Also I've tried options BUILD_STATIC & BUILD_STATIC_PIC, though I assume only BUILD_STATIC is necesarry.

**Comment by joaqim** [comment]
CMake output with gcc4.8 : [https://pastebin.com/raw/BNHEsFcQ](https://pastebin.com/raw/BNHEsFcQl)

**Comment by joaqim** [comment]
Got it working when removing some CMake addtional variables such as DCMAKE_INSTALL_PREFIX and {MAGNUM,CORRADE}_INCLUEDE_INSTALL_PREFIX, seems the Error was on my part. 
Will investigate further.

**Comment by mosra** [comment]
Thanks for the extensive details :+1: 

I just tried recompiling everything here (I have `android-ndk` r16.b though, so Clang 5 ... though I don't expect that the upgrade would break things this much) and experiencing no such errors. Moreover, [line 84 in Attribute.h](https://github.com/mosra/magnum/blob/86888194232c397ad5bb220da8f32cf777073057/src/Magnum/GL/Attribute.h#L84) (from your report above) looks different than in current master, are you sure you have a clean working copy of Magnum?

I am on a new dev machine so I have just the NDK installed, no Gradle or anything for building the actual `*.apk`s. Will report back once I have the gallery running on my phone. I'll also try with the new NDK.

**Comment by Joaqim** [comment]
Sorry, deleted the extensive comments since I though i solved it by simply removing superflous CMake variable, such as DMAGNUM_INCLUDE_DIR.

I was mistaken and the build failed as before. I will try installing a new clean magnum from git.

**Comment by Joaqim** [comment]
Seems the problem might be with my CMAKE_INSTALL_PREFIX,
Might take some time for me to clean up my android-ndk/sysroot and find where everything should be put.

Thanks for the help, will update soon.

**Comment by Joaqim** [comment]
No change (still getting the same errors as the first post), feel like I'm back to square one. 
I will continue to try to see if maybe it's a faulty include but I'm not optimistic.
The line:84 in Attribute.h was probably changed when I made a naive attempt att forward declaring Attribute<int> etc.

I'm going to see if the error is with my android-ndk platform, reinstalling might take some time.

Is it safe to disregard linker error? Since the compile seems to fail in include/template instantiation stage.

**Comment by mosra** [comment]
huh okay, let me try with latest NDK. You have r17-1, right?

**Comment by Joaqim** [comment]
Latest Android-Ndk r17-1

My build script is using:
target=armeabi-v7a
arch=arch-arm
sdk=22

'cmake .. \
	-DCORRADE_TARGET_ANDROID=ON \
	-DCMAKE_SYSTEM_NAME=Android \
	-DCMAKE_SYSTEM_VERSION=${sdk} \
	-DCMAKE_ANDROID_ARCH_ABI="${target}" \
	-DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang \
	-DCMAKE_ANDROID_STL_TYPE=c++_static \
	-DANDROID_STL=c++_static \
	-DANDROID_NDK=/opt/android-ndk \
	-DANDROID_NDK_MINOR=${sdk} \
	-DBUILD_STATIC=ON \
	-DMAGNUM_INCLUDE_INSTALL_PREFIX=/opt/android-ndk/sysroot/usr \
	-DCORRADE_INCLUDE_INSTALL_PREFIX=/opt/android-ndk/sysroot/usr \
	-DCMAKE_INSTALL_PREFIX=/opt/android-ndk/platforms/android-${sdk}/${arch}/usr \
	-DCMAKE_BUILD_TYPE=Release '

Full script: [https://pastebin.com/9UQgbFBL](https://pastebin.com/raw/9UQgbFBL)

I started with using the cmake command found PKGBUILD-android-arm64 used in build() and added a lot while trying to make it complie with Ui .

**Comment by Joaqim** [comment]
I can't seem to compile magnum with TARGET_DESKTOP_GLES & WITH_WINDOWLESSEGLAPPLICATION.
"missing -lgl".

Will investigate further.

**Comment by mosra** [comment]
Installing latest NDK here.

> I started with using the cmake command found PKGBUILD-android-arm64 used in build() and added a lot while trying to make it complie with Ui .

But doesn't the PKGBUILD have everything needed already? It's also enabling the Ui library, just not the gallery, because that one needs to be built with Gradle.

> I can't seem to compile magnum with TARGET_DESKTOP_GLES

On Android? Desktop GLES is not available on Android, there's no libGL. This is for OpenGL ES emulation on desktop systems.

**Comment by Joaqim** [comment]
You are right, I was just naively trying different options building Magnum.

**Comment by mosra** [comment]
Hmm, installed NDK r17 and still can't reproduce :/ Even tried your script from above, still no luck, the Ui library just builds.

I'm running out of ideas... Can you run `make VERBOSE=1` and post the full compiler command-line when compiling Plane.cpp? I suspect there is some global define or something that causes this problem.

**Comment by Joaqim** [comment]
make VERBOSE=1 [https://pastebin.com/JZHnxHnn](https://pastebin.com/raw/JZHnxHnn)

I will clean up my system and try to compile again. But how should I proberly install the PKGBUILDS without conflict? Seems weird to me to only be able to compile for either Android or Unix at any time, maybe I missunderstand how it works.

Going off for a while, will see about it tonight/tomorrow, thanks for all the help, didn't have much luck with google except 'missing header include' which doesn't seem to be the problem.

**Comment by mosra** [comment]
Ahhh. Now it dawned on me. You're compiling for GLES 2.0, right?

At the moment the Ui library doesn't support that (it uses uniform buffers, integer attributes and some more features from ES3). I'll try to backport it at some point, but at the moment it won't work with ES2.

Sorry about the wasted time here. There should have been a big error up-front, not something *this deep down* in the code.

**Comment by Joaqim** [comment]
Ahh will see if I can fix it later, thank you, I was very confused which graphic front-end I was supposed to use at compile. I just used the Platform:: specific stuff for android code and SDL_Context for my own OpenGL drawing on computer.

**Comment by mosra** [comment]
Damn, it should be documented better, sorry. I thought I put it on the [Android](http://doc.magnum.graphics/magnum/platforms-android.html) page, but it's not there :/ Will put more effort into that.

You can use Sdl2Application on desktop and AndroidApplication on Android, as shown here: https://github.com/mosra/magnum-bootstrap/blob/base-android/src/MyApplication.cpp 

Some more info is also [here](http://doc.magnum.graphics/magnum/portability.html#portability-applications).

**Comment by Joaqim** [comment]
Thanks for everything, had some time to completely remove my android-ndk directory and re-install everything. It now works flawlessly ^ ^ . 
So the error was simply linking Gles2 instead of Gles3 while compiling for Android.
I opened the issue since I was stumped with the type instantiation error. But the error was a simple linker error.

**Comment by mosra** [comment]
Just for the record: since 1cd4e56da0090c64a62cbbb3c0b36f9eb695058b CMake properly fails with a reasonable error message if one attempts to build it for ES2 or WebGL 1.
