### ISSUE TITLE
Ui: Add method to get hovered widget(s)

### ISSUE THREAD

**Issue by Squareys** [mosra/magnum-extras#8]
Hi @mosra !

As per gitter, I have a use case (some drop event) where I would like to be able to query the hovered widget(s) (e.g. the toplevel widget of some stack as you suggested).

Cheers, Jonathan

**Comment by mosra** [comment]
The UI lib got completely replaced with a new implementation as of 9d42ea49234c696ea59abdf7b9d2ef11a50f87b1 + f560d2381b5bae3bf20f7a95552370a7a6dd3e00, and this is no longer relevant. Documentation is still rather sparse, but the order of stacked widgets / nodes can be iterated through [Ui::AbstractUserInterface::nodeOrderFirst()](https://doc.magnum.graphics/magnum/classMagnum_1_1Ui_1_1AbstractUserInterface.html#a2048fcde7027d92d29cd9c5b0f19e107) and [nodeOrderNext()](https://doc.magnum.graphics/magnum/classMagnum_1_1Ui_1_1AbstractUserInterface.html#a357dcc33006c3a85243d0148fc02bc7e).
